# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   # This workflow contains a single job called "build"
#  test:
          
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: wget
        run: |
          choco install wget 
      - name: build bandwhich
        shell: bash
        run: |
          bash
          wget https://github.com/imsnif/bandwhich/archive/refs/tags/0.20.0.tar.gz
          tar zxvf 0.20.0.tar.gz
          printf "%s\n" "开始编译"
          cd bandwhich-0.20.0/ && {
            cargo update
            rustc --explain E0512
            rustc --explain E0793
            cargo build -r
            mv target/release  $GITHUB_WORKSPACE/
          }
          printf "%s\n" "编译结束"
      - name: compression
        run: |
          cd  $GITHUB_WORKSPACE
          7z a bandwhich.7z $GITHUB_WORKSPACE/release
      - uses: actions/upload-artifact@v3
        with:
          path: bandwhich.7z
          name: bandwhich