# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on:  macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: |
          brew update && brew install gcc g++ make automake autoconf libtool pkgconfig curl sdl2
      - name: static build
        run: |
          dir="$(pwd)"
          (
              curl -LO https://github.com/ggerganov/whisper.cpp/archive/refs/tags/v1.5.4.tar.gz
              tar xvf v1.5.4.tar.gz
              cd whisper.cpp-1.5.4/ && {
                make
                make command talk talk-llama lsp stream
                command mkdir ${dir}/whisper 
                cp -r *.o main stream command talk talk-llama bench quantize server lsp libwhisper.a libwhisper.so ${dir}/whisper || true
              }
          )

          (
            cd "${dir}" && {
              tar cJvf whisper.tar.xz whisper
            }
          )
      - uses: actions/upload-artifact@v3
        with:
          path: "whisper.tar.xz"
          name: "whisper"